### PR TITLE
Added summon/sacrifice mechanic

### PR DESCRIPTION
**Pull request by DeanMSalter**
Added the ability to right click a block with an item and it fetch your angelchest to you.

### CODE REVIEW

**Comment by mfnalex** [comment]
Thanks <3 I will look at it and probably merge it tomorrow once I'm at home - if I forget, please nag me on discord to remind me^^

**Comment by mfnalex** [comment]
What exactly does "summoning"/"sacrificing" do? I don't really understand, please explain :)

**Comment by Cazcez** [comment]
> What exactly does "summoning"/"sacrificing" do? I don't really understand, please explain :)

Not sure but looks like you can get your angelchest if you have summon block but you need to sacrifice an item as an cost for getting your angelchest

**Comment by DeanMSalter** [comment]
So if the player right-clicks a specific block while holding a specific item, it will remove the item they are holding and fetch the chest to them, the same way the fetch command works.

**Pull request merged**
